#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : Subsystem.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Apr 10 14:21:50 -0600 2021
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: Subsystem.sh [-help]
# usage: Subsystem.sh [-lib_map_path]
# usage: Subsystem.sh [-noclean_files]
# usage: Subsystem.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'Subsystem.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_24 proc_sys_reset_v5_0_13 v_tc_v6_2_1 xlconcat_v2_1_4 xlconstant_v1_1_7)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "Subsystem.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d0f7" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d0f7" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_PmodOLED_0_0/Subsystem_PmodOLED_0_0_sim_netlist.vhdl" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_axi_dma_0_0/Subsystem_axi_dma_0_0_sim_netlist.vhdl" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_axi_gpio_1_0/sim/Subsystem_axi_gpio_1_0.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_axi_gpio_2_0/sim/Subsystem_axi_gpio_2_0.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_xbar_0/Subsystem_xbar_0_sim_netlist.vhdl" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_axi_vdma_0_0/Subsystem_axi_vdma_0_0_sim_netlist.vhdl" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_clk_wiz_0_0/Subsystem_clk_wiz_0_0_sim_netlist.vhdl" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_processing_system7_0_0/Subsystem_processing_system7_0_0_sim_netlist.vhdl" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_xbar_1/Subsystem_xbar_1_sim_netlist.vhdl" \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d57c/src/ClockGen.vhd" \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d57c/src/SyncAsync.vhd" \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d57c/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d57c/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d57c/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d57c/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d57c/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_rgb2dvi_0_0/sim/Subsystem_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_rst_clk_wiz_0_148M_0/sim/Subsystem_rst_clk_wiz_0_148M_0.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_v_axi4s_vid_out_0_0/Subsystem_v_axi4s_vid_out_0_0_sim_netlist.vhdl" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_2_1 $vhdlan_opts \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/cd2e/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_v_tc_0_0/sim/Subsystem_v_tc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d0f7" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d0f7" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_xlconcat_1_0/sim/Subsystem_xlconcat_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d0f7" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/d0f7" +incdir+"$ref_dir/../../../../DTOFLS.gen/sources_1/bd/Subsystem/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_xlconstant_0_0/sim/Subsystem_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_Input_Debounce_0_0/sim/Subsystem_Input_Debounce_0_0.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_Input_Debounce_0_1/sim/Subsystem_Input_Debounce_0_1.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_Input_Debounce_1_0/sim/Subsystem_Input_Debounce_1_0.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_Input_Debounce_1_1/sim/Subsystem_Input_Debounce_1_1.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_Input_Debounce_1_2/sim/Subsystem_Input_Debounce_1_2.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_Input_Debounce_1_3/sim/Subsystem_Input_Debounce_1_3.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_Input_Debounce_1_4/sim/Subsystem_Input_Debounce_1_4.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_axi_gpio_1_1/sim/Subsystem_axi_gpio_1_1.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_axi_gpio_1_2/sim/Subsystem_axi_gpio_1_2.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_axi_gpio_1_3/sim/Subsystem_axi_gpio_1_3.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_axi_gpio_4_0/sim/Subsystem_axi_gpio_4_0.vhd" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_axi_gpio_4_1/sim/Subsystem_axi_gpio_4_1.vhd" \
    "$ref_dir/d:/PERSONAL/Projects/DTOFLS/DTOFLS.gen/sources_1/bd/Subsystem/ip/Subsystem_imageProcessTop_0_0/Subsystem_imageProcessTop_0_0_sim_netlist.vhdl" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_auto_us_0/Subsystem_auto_us_0_sim_netlist.vhdl" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_auto_us_1/Subsystem_auto_us_1_sim_netlist.vhdl" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_auto_pc_0/Subsystem_auto_pc_0_sim_netlist.vhdl" \
    "$ref_dir/../../../bd/Subsystem/ip/Subsystem_auto_pc_1/Subsystem_auto_pc_1_sim_netlist.vhdl" \
    "$ref_dir/../../../bd/Subsystem/sim/Subsystem.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.Subsystem xil_defaultlib.glbl -o Subsystem_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./Subsystem_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./Subsystem.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key Subsystem_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc Subsystem_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./Subsystem.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: Subsystem.sh [-help]\n\
Usage: Subsystem.sh [-lib_map_path]\n\
Usage: Subsystem.sh [-reset_run]\n\
Usage: Subsystem.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
