# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/PERSONAL/Projects/DTOFLS/DTOFLS.srcs/sources_1/bd/Subsystem/ip/Subsystem_clk_wiz_0_0/Subsystem_clk_wiz_0_0.xci
# IP: The module: 'Subsystem_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PERSONAL/Projects/DTOFLS/DTOFLS.gen/sources_1/bd/Subsystem/ip/Subsystem_clk_wiz_0_0/Subsystem_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Subsystem_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/PERSONAL/Projects/DTOFLS/DTOFLS.gen/sources_1/bd/Subsystem/ip/Subsystem_clk_wiz_0_0/Subsystem_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Subsystem_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/PERSONAL/Projects/DTOFLS/DTOFLS.gen/sources_1/bd/Subsystem/ip/Subsystem_clk_wiz_0_0/Subsystem_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Subsystem_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/PERSONAL/Projects/DTOFLS/DTOFLS.srcs/sources_1/bd/Subsystem/ip/Subsystem_clk_wiz_0_0/Subsystem_clk_wiz_0_0.xci
# IP: The module: 'Subsystem_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PERSONAL/Projects/DTOFLS/DTOFLS.gen/sources_1/bd/Subsystem/ip/Subsystem_clk_wiz_0_0/Subsystem_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Subsystem_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/PERSONAL/Projects/DTOFLS/DTOFLS.gen/sources_1/bd/Subsystem/ip/Subsystem_clk_wiz_0_0/Subsystem_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Subsystem_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/PERSONAL/Projects/DTOFLS/DTOFLS.gen/sources_1/bd/Subsystem/ip/Subsystem_clk_wiz_0_0/Subsystem_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Subsystem_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
