# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/Zybo_Z7.xdc

# Block Designs: bd/Subsystem/Subsystem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem || ORIG_REF_NAME==Subsystem} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_PmodOLED_0_0/Subsystem_PmodOLED_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_PmodOLED_0_0 || ORIG_REF_NAME==Subsystem_PmodOLED_0_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_axi_dma_0_0/Subsystem_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_axi_dma_0_0 || ORIG_REF_NAME==Subsystem_axi_dma_0_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_axi_gpio_1_0/Subsystem_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_axi_gpio_1_0 || ORIG_REF_NAME==Subsystem_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_axi_gpio_2_0/Subsystem_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_axi_gpio_2_0 || ORIG_REF_NAME==Subsystem_axi_gpio_2_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_xbar_0/Subsystem_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_xbar_0 || ORIG_REF_NAME==Subsystem_xbar_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_axi_mem_intercon_0/Subsystem_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_axi_mem_intercon_0 || ORIG_REF_NAME==Subsystem_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_axi_vdma_0_0/Subsystem_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_axi_vdma_0_0 || ORIG_REF_NAME==Subsystem_axi_vdma_0_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_clk_wiz_0_0/Subsystem_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_clk_wiz_0_0 || ORIG_REF_NAME==Subsystem_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_processing_system7_0_0/Subsystem_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_processing_system7_0_0 || ORIG_REF_NAME==Subsystem_processing_system7_0_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_xbar_1/Subsystem_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_xbar_1 || ORIG_REF_NAME==Subsystem_xbar_1} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_ps7_0_axi_periph_0/Subsystem_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_ps7_0_axi_periph_0 || ORIG_REF_NAME==Subsystem_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_rgb2dvi_0_0/Subsystem_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_rgb2dvi_0_0 || ORIG_REF_NAME==Subsystem_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_rst_clk_wiz_0_148M_0/Subsystem_rst_clk_wiz_0_148M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_rst_clk_wiz_0_148M_0 || ORIG_REF_NAME==Subsystem_rst_clk_wiz_0_148M_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_v_axi4s_vid_out_0_0/Subsystem_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==Subsystem_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_v_tc_0_0/Subsystem_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_v_tc_0_0 || ORIG_REF_NAME==Subsystem_v_tc_0_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_xlconcat_1_0/Subsystem_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_xlconcat_1_0 || ORIG_REF_NAME==Subsystem_xlconcat_1_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_xlconstant_0_0/Subsystem_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_xlconstant_0_0 || ORIG_REF_NAME==Subsystem_xlconstant_0_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_Input_Debounce_0_0/Subsystem_Input_Debounce_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_Input_Debounce_0_0 || ORIG_REF_NAME==Subsystem_Input_Debounce_0_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_Input_Debounce_0_1/Subsystem_Input_Debounce_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_Input_Debounce_0_1 || ORIG_REF_NAME==Subsystem_Input_Debounce_0_1} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_Input_Debounce_1_0/Subsystem_Input_Debounce_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_Input_Debounce_1_0 || ORIG_REF_NAME==Subsystem_Input_Debounce_1_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_Input_Debounce_1_1/Subsystem_Input_Debounce_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_Input_Debounce_1_1 || ORIG_REF_NAME==Subsystem_Input_Debounce_1_1} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_Input_Debounce_1_2/Subsystem_Input_Debounce_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_Input_Debounce_1_2 || ORIG_REF_NAME==Subsystem_Input_Debounce_1_2} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_Input_Debounce_1_3/Subsystem_Input_Debounce_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_Input_Debounce_1_3 || ORIG_REF_NAME==Subsystem_Input_Debounce_1_3} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_Input_Debounce_1_4/Subsystem_Input_Debounce_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_Input_Debounce_1_4 || ORIG_REF_NAME==Subsystem_Input_Debounce_1_4} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_axi_gpio_1_1/Subsystem_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_axi_gpio_1_1 || ORIG_REF_NAME==Subsystem_axi_gpio_1_1} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_axi_gpio_1_2/Subsystem_axi_gpio_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_axi_gpio_1_2 || ORIG_REF_NAME==Subsystem_axi_gpio_1_2} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_axi_gpio_1_3/Subsystem_axi_gpio_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_axi_gpio_1_3 || ORIG_REF_NAME==Subsystem_axi_gpio_1_3} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_axi_gpio_4_0/Subsystem_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_axi_gpio_4_0 || ORIG_REF_NAME==Subsystem_axi_gpio_4_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_axi_gpio_4_1/Subsystem_axi_gpio_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_axi_gpio_4_1 || ORIG_REF_NAME==Subsystem_axi_gpio_4_1} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_imageProcessTop_0_0/Subsystem_imageProcessTop_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_imageProcessTop_0_0 || ORIG_REF_NAME==Subsystem_imageProcessTop_0_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_auto_us_0/Subsystem_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_auto_us_0 || ORIG_REF_NAME==Subsystem_auto_us_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_auto_us_1/Subsystem_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_auto_us_1 || ORIG_REF_NAME==Subsystem_auto_us_1} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_auto_pc_0/Subsystem_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_auto_pc_0 || ORIG_REF_NAME==Subsystem_auto_pc_0} -quiet] -quiet

# IP: bd/Subsystem/ip/Subsystem_auto_pc_1/Subsystem_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Subsystem_auto_pc_1 || ORIG_REF_NAME==Subsystem_auto_pc_1} -quiet] -quiet

# XDC: d:/PERSONAL/Projects/DTOFLS/DTOFLS.gen/sources_1/bd/Subsystem/Subsystem_ooc.xdc
